import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const getFont = Poppins({
  subsets:["latin"],
  weight:["400" ,"600"],
  display :"swap"
})

export const metadata = {
  title: "My Tour guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en">
      <body className={'${getFont.className}  w-screen h-screen bg-black'}>
        <Nav/>
        {children}
        </body>
    </html>
  );
}
